const { env } = process
const { LOG_LEVEL, STAGE, REGION, DDB_TABLE, AWS_API_VERSION, KMS_KEY_ID_AUTH, KMS_KEY_ID_PASSWORD, SENDWELL_SUPPORT_EMAIL, OTP_EXPIRATION_MINUTES, SENDWELL_PROFILE_IMAGES } = env

const Config = {
  LOG_LEVEL: LOG_LEVEL || 'silly',
  STAGE: STAGE || 'dev',
  REGION: REGION || 'us-east-2',
  DDB_TABLE: DDB_TABLE || `user-service-${STAGE}`,
  AWS_API_VERSION: AWS_API_VERSION || '2012-08-10',
  KMS_KEY_ID_AUTH: KMS_KEY_ID_AUTH || '26fa0003-57fa-4b21-90a3-f978f10096a1',
  KMS_KEY_ID_PASSWORD: KMS_KEY_ID_PASSWORD || '15deceb0-579f-4950-871a-2025e9a15acc',
  SENDWELL_SUPPORT_EMAIL: SENDWELL_SUPPORT_EMAIL || 'devs@rsolve.co',
  OTP_EXPIRATION_MINUTES: Number(OTP_EXPIRATION_MINUTES) || 15,
  SENDWELL_PROFILE_IMAGES: SENDWELL_PROFILE_IMAGES || `sendwell-profile-images-${STAGE}`
}

export default Config
